@startuml 

hide circle

entity "Artist" {
  ID: string
  --
  name: string
  url: string
  iconUrl: string
  timestamp: timestamp
}

entity "Relate" {
  relate_id: string
  --
  name1: string <<FK>>
  name2: string <<FK>>
}

Artist ||..o{ Relate
@enduml